# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-24 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('building', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('raw', models.CharField(max_length=100, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='metro',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='metro',
            name='line_id',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='metro',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='metro_stations',
            field=models.ManyToManyField(to='vacancies.Metro'),
        ),
    ]
