# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-25 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20171124_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(max_length=30, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='address',
            name='metro_stations',
            field=models.ManyToManyField(to='vacancies.Metro', verbose_name='Станции метро'),
        ),
        migrations.AlterField(
            model_name='address',
            name='raw',
            field=models.CharField(max_length=100, null=True, verbose_name='Оригинал строки адреса'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='metro',
            name='line_name',
            field=models.CharField(max_length=30, verbose_name='Ветка метро'),
        ),
        migrations.AlterField(
            model_name='metro',
            name='station_name',
            field=models.CharField(max_length=30, verbose_name='Станция метро'),
        ),
    ]
